colors:
  body: none
  date: black
  tags: yellow
  title: green
default_hour: 9
default_minute: 0
editor: nvim -c $ -c startinsert!
encrypt: false
highlight: true
indent_character: ""
journals:
  :1688:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Items\1688Journal.md
  acc:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\secret\AccountJournal.md
  acro:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\AcronymJournal.md
  cad3d:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\CAD\CADJournal.md
  draw:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\Art\ArtToolsJournal.md
  blend:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\Art\ArtToolsJournal.md
  art:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\Art\ArtToolsJournal.md
  asset:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Items\AssetJournal.md
  blog:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\ReadAndListenJournal.md
  book:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\ReadAndListenJournal.md
  cad:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\CAD\CADJournal.md
  come:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\WholesomeJournal.md
  inte:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ProtocolJournal.md
  prot:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ProtocolJournal.md
  bus:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ProtocolJournal.md
  wire:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ProtocolJournal.md
  comp:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ComponentJournal.md
  default:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\MainJournal.md
  eco:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\EconomyJournal.md
  econ:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\EconomyJournal.md
  ecad:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\note_EDA\EDAJournal.md
  eda:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\note_EDA\EDAJournal.md
  edit:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\Art\ArtToolsJournal.md
  embed:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_algo_lang\journal\ProgrammingJournal.md
  ev:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\EventJournal.md
  event:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\EventJournal.md
  firm:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\FirmwareJournal.md
  fw:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\FirmwareJournal.md
  hard:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\HardwareJournal.md
  hh:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\WholesomeJournal.md
  hw:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\HardwareJournal.md
  item:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Items\OtherItemsJournal.md
  kicad:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\note_EDA\EDAJournal.md
  lang:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_algo_lang\journal\LangJournal.md
  tip:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\LifeHackJournal.md
  ltip:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\LifeHackJournal.md
  lhack:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\LifeHackJournal.md
  hack:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\LifeHackJournal.md
  life:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\LifeJournal.md
  linux:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_software\journal\OSJournal.md
  lowsw:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\FirmwareJournal.md
  math:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_algo_lang\journal\STEMJournal.md
  mech:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\CAD\CADJournal.md
  media:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\NewsJournal.md
  meme:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\WholesomeJournal.md
  new:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\NewsJournal.md
  news:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\NewsJournal.md
  os:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_software\journal\OSJournal.md
  other:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\OtherKnowledgeJournal.md
  people:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\PeopleJournal.md
  per:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\PeopleJournal.md
  person:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\PeopleJournal.md
  phr:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\PhraseJournal.md
  phrase:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\PhraseJournal.md
  physic:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_algo_lang\journal\STEMJournal.md
  place:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\PlacesJournal.md
  prog:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_algo_lang\journal\ProgrammingJournal.md
  qt:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\PhraseJournal.md
  quote:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\PhraseJournal.md
  read:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\ReadAndListenJournal.md
  soft:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_software\journal\SoftwareJournal.md
  stem:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_algo_lang\journal\STEMJournal.md
  stm:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\FirmwareJournal.md
  sw:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_software\journal\SoftwareJournal.md
  taobao:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Items\TaobaoJournal.md
  til:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\OtherKnowledgeJournal.md
  mus:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_entertainment\note_discography\MusicJournal.md
  music:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_entertainment\note_discography\MusicJournal.md
  vid:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_entertainment\note_discography\VideoJournal.md
  video:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_entertainment\note_discography\VideoJournal.md
  vocab:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Knowledge\journal\VocabJournal.md
  web:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_software\journal\WebJournal.md
  wf:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Business\WorkflowJournal.md
  windows:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_software\journal\OSJournal.md
  work:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Business\WorkJournal.md
  workflow:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Business\WorkflowJournal.md
  freecad:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\CAD\CADJournal.md
  fcad:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_IDEAndTools\Asset\CAD\CADJournal.md
  module:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ChipsetJournal.md
  ic:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ChipsetJournal.md
  chip:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ChipsetJournal.md
  soc:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\ChipsetJournal.md
  html:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_os_web\SDK\WebProgJournal.md
  wasm:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_os_web\SDK\WebProgJournal.md
  wprog:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_os_web\SDK\WebProgJournal.md
  wpro:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_os_web\SDK\WebProgJournal.md
  pcb:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\PCB_Standard\PCBJournal.md
  viap:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\PCB_Standard\PCBJournal.md
  pcba:
    journal: D:\ProgramDataD\Notes\Obsidian\Vault_2401\note_Embedded\PCB_Standard\PCBJournal.md

linewrap: 2000
tagsymbols: "#@"
template: false
timeformat: "%F %r"
version: v4.1
